---
- name: Show commands list output to the file
  hosts: nexus1
  gather_facts: false
  connection: local
  vars:
   command_list:
        # - show etherchannel summary
          - show run
          - show mac address-table
        # - sh switch stack-ports
        # - sh switch
        # - show environment all
        # - show ip ospf int brief
        # - show ip ospf neigh
          - show cdp neighbors detail
          - show version
        # - show license usage
        # - show clock
        # - show users
        # - show boot
        # - show int status | inc connected
        # - show arp
          - show ip interface brief | exc admin

  tasks:
   - name: Run the SHOW commands and save output
     nxos_command:
      commands: "{{ command_list }}"
     register: showoutput

   - name: "Put all the files together into one nice text file"
     template:
      src: template.j2
      dest: "./backups/{{ inventory_hostname }}-showoutput.txt"
